# Generated by Django 4.2.6 on 2023-11-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_embedding', '0002_documento_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='media/archivos_csv/'),
        ),
    ]
