# Generated by Django 4.2.6 on 2023-11-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_embedding', '0003_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='media/archivos_xslx/'),
        ),
    ]
